name: Auto commit
on: pull_request
permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: 22479998

      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ steps.github_app_token.outputs.token }}

      - name: Formatting
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run format
          
      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: Updating SHAs
          branch: ${{ github.head_ref }}
          commit_user_name: Vacha
          commit_user_email: vachshah@amazon.com
          commit_options: '--signoff'
