name: Auto commit
on: pull_request
permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'VachaShah' }}
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: 22479998

      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ steps.github_app_token.outputs.token }}
          ref: ${{ env.BASE }}

      - name: Editing file
        run: |
          echo Changing the file
          
      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: Committing changes
          branch: ${{ github.head_ref }}
          commit_user_name: Vacha
          commit_user_email: vachshah@amazon.com
          commit_options: '--signoff'

      - name: Show GitHub context   
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}   
        run: echo "$GITHUB_CONTEXT"
        shell: bash
