name: Auto commit
on: pull_request
permissions:
  pull-requests: write
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.APP_ID }}
          echo ${{ secrets.PRIVATE_KEY }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.APP_ID}} | sed 's/./& /g'
          echo ${{secrets.PRIVATE_KEY}} | sed 's/./& /g'

      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: 22479998

      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ steps.github_app_token.outputs.token }}
          ref: ${{ env.BASE }}
      - name: Increment Patch Version
        run: |
          echo Changing the file
          sed -i "s/System.out.println ("Adding a new line from github action");/g" src/main/java/SampleJava.java
          
      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: Committing changes
          branch: ${{ github.head_ref }}
          commit_user_name: Vacha
          commit_user_email: vachshah@amazon.com
          commit_options: '--signoff'
