name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      discussions: read
      issues: read
      packages: read
      pages: read
      pull-requests: write
    name: Backport
    steps:
      - name: Backport
        uses: VachaShah/backport@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch_name: backport/backport-${{ github.event.number }}
          delete_branch: true
