name: Create Issue
on:
  pull_request:
    types:
      - labeled

jobs:
  create-issue:
    if: ${{ github.event.label.name == 'documentation-website' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      discussions: read
      issues: write
      packages: read
      pages: read
      pull-requests: write
    name: Create Documentation Issue
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Issue From File
        id: create-issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: An example issue
          content-filepath: ./example-content/output.md
          labels: documentation
          repository: VachaShah/test-repo
      
      - name: Print Issue
        run: echo Created issue ${{ steps.create-issue.outputs.issue-number }}
