name: Create Issue
on:
  pull_request:
    types:
      - labeled
env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  create-issue:
    if: ${{ github.event.label.name == 'documentation-website' }}
    runs-on: ubuntu-latest
    name: Create Documentation Issue
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: 22479998

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Edit the issue template
        run: |
          echo "https://github.com/VachaShah/OpenSearch/pull/${{ env.PR_NUMBER }}." >> ./example-content/output.md
          
      - name: Create Issue From File
        id: create-issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Documentation related to feature
          content-filepath: ./example-content/output.md
          labels: documentation
          repository: VachaShah/test-repo
          token: ${{ steps.github_app_token.outputs.token }}
      
      - name: Print Issue
        run: echo Created issue ${{ steps.create-issue.outputs.issue-number }}
