name: Backport
on:
  pull_request:
    types:
      - labeled

jobs:
  create-issue:
    if: ${{ github.event.label.name == 'documentation-website' }}
    runs-on: ubuntu-latest
    name: Create Documentation Issue
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: 22479998

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: An example issue
          content-filepath: ./example-content/output.md
          labels: documentation
          repository: VachaShah/test-repo
          token: ${{ steps.github_app_token.outputs.token }}
