name: Delete merged branch of the backport PRs
on: 
  pull_request:
    branches: 
      - backport/*
    types:
      - closed
  
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}