name: Link Checker
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linkchecker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.2.0
        with:
          args: --accept=200,403,429 --exclude-mail **/*.html **/*.md **/*.txt **/*.json
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
