on: [push, pull_request]
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: ./ # Uses an action in the root directory
        with:
          args: --verbose --no-progress --exclude lycheeverse/lychee-action@.* -- **/*.md **/*.html **/*.txt **/*.json
